### ISSUE TITLE
The hook is not working with my project

### ISSUE THREAD

**Issue by C0ZEN** [uglow/cz-customizable-ghooks#13]
Hello,
I can not seem to make this work.

Using for example:

`git commit -m "chorre(hooks): just testing hooks"`

Will not abort the commit.
The word `chorre` is clearly misspelled and is not allowed in the types.

**Configuration:**

*package.json*

```
"config": {
  "commitizen": {
    "path": "./node_modules/cz-customizable"
  },
  "cz-customizable": {
    "config": "./scripts/commitizen.js"
  }
},
"scripts": {
  "commitmsg": "cz-customizable-ghooks"
}
```

*commitizen.js*

```
module.exports = {
  allowBreakingChanges: [`feat`, `fix`, `build`],
  allowCustomScopes: true,
  allowTicketNumber: false,
  isTicketNumberRequired: false,
  messages: {
    body: `Provide a LONGER description of the change (optional). Use "|" to break new line:\n`,
    breaking: `List any BREAKING CHANGES (optional):\n`,
    confirmCommit: `Are you sure you want to proceed with the commit above ?`,
    customScope: `SCOPE of this change:`,
    scope: `\nSCOPE of this change (optional):`,
    subject: `Write a SHORT, IMPERATIVE tense subject of the change:\n`,
    type: `Select the type of change that you are committing:`,
  },
  skipQuestions: [`footer`],
  subjectLimit: 144,
  // Any changes should also me made on the [semantic config](#/.github/semantic.yml)
  types: [
    {
      name: `feat:     A new feature`,
      value: `feat`,
    },
    {
      name: `fix:      A bug fix`,
      value: `fix`,
    },
    {
      name: `style:    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)`,
      value: `style`,
    },
    {
      name: `refactor: A code change that neither fixes a bug nor adds a feature`,
      value: `refactor`,
    },
    {
      name: `perf:     A code change that improves performance`,
      value: `perf`,
    },
    {
      name: `test:     Adding missing tests or correcting existing tests`,
      value: `test`,
    },
    {
      name: `build:    Changes that affect the build system, CI configuration or external dependencies`,
      value: `build`,
    },
    {
      name: `chore:    Anything else`,
      value: `chore`,
    },
  ],
};

```

**Dependencies:**

```
- "commitizen": "4.1.2"
- "cz-customizable": "6.2.0"
- "cz-customizable-ghooks": "1.5.0"
- "husky": "4.2.5"
```

My repo issue:
https://github.com/Sonia-corporation/il-est-midi-discord/issues/335

**Comment by C0ZEN** [comment]
@uglow just checking. Is this project still maintained?

**Comment by uglow** [comment]
Hi @C0ZEN , sorry for the delay in responding.

There's a couple of things that may help:
- The `git cz` command activates commitizen. Doing `git commit ...` does not activate commitizen
- If you want to your commit messages to be checked without using `git cz`, the [README.md](../blob/master/README.md) says, "3. Install One of these git hook packages" and then configure the hook as described in the README.

**Comment by C0ZEN** [comment]
@uglow thank you for the response.
I will make sure that everything you say is well configured on my project and reach out again once done.

**Comment by C0ZEN** [comment]
@uglow
- [x] Required dependencies installed
- [x] cz-customizable configured in the package
- [x] `commitmsg` script configured in the package
- [x] Git version recent enough for husky `2.19.2`
- [x] `npm rebuild` to ensure hooks are installed

I dunno what to expect from running `commitmsg` manually but anyway here is the stacktrace:

```
S:\C0ZEN\Documents\sonia\il-est-midi-discord\node_modules\cz-customizable-ghooks\lib\index.js:205
    throw new Error('commitMsgFileName must be the path to the "COMMIT_EDITMSG" file (usually ".git/COMMIT_EDITMSG")');
    ^

Error: commitMsgFileName must be the path to the "COMMIT_EDITMSG" file (usually ".git/COMMIT_EDITMSG")
    at processCLI (S:\C0ZEN\Documents\sonia\il-est-midi-discord\node_modules\←[4mcz-customizable-ghooks←[24m\lib\index.js:205:11)
    at Object.<anonymous> (S:\C0ZEN\Documents\sonia\il-est-midi-discord\node_modules\←[4mcz-customizable-ghooks←[24m\lib\index.js:249:3)
```

I tried to use this config after that for husky:

```
{
  "hooks": {
    "pre-commit": "lint-staged && npm run commitmsg",
    "post-commit": "git update-index --again"
  }
}
```

Then `npm rebuild` and commit.
Same error than above.

**Comment by dmwelch** [comment]
I was having the same problem using `husky` v1.3.1 on OSX but upgrading to 4.2.5 seemed to fix the error for me but the linting doesn't throw an error for something like `$ git commit -am "hello: world"` 

Installing `@commitlint/core` and adding a `commitlint.config.js` file did not solve the problem.  Any ideas?  Here's my setup (without the commitlint details):

```bash
$ git --version
git version 2.23.0
```
---
package.json:
```json5
{
  ...
  "scripts": {
    "commitmsg": "cz-customizable-ghooks",
    ...
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-customizable"
    },
    "cz-customizable": {
      "config": "./cz-config.js"
    }
  },
  "husky": {
    "hooks": {
      "pre-commit": "eslint public --ext .js,.jsx && eslint test --ext .js",
      "pre-push": "jest --config .jestrc.json"
    },
    ...
  },
  ...
  "devDependencies": {
    "commitizen": "4.2.0",
    "cz-customizable": "6.3.0",
    "cz-customizable-ghooks": "1.5.0",
    "husky": "4.2.5",
    ...
  },
  "engines": {
    "node": "12.13.1"
  }
}
```
---
cz-config.js:
```javascript
module.exports = {
  types: [
    { value: 'feat', name: 'feat:     A new feature' },
    { value: 'fix', name: 'fix:      A bug fix' },
    { value: 'docs', name: 'docs:     Documentation only changes' },
    {
      value: 'style',
      name:
        'style:    Changes that do not affect the meaning of the code\n            (white-space, formatting, missing semi-colons, etc)',
    },
    {
      value: 'refactor',
      name: 'refactor: A code change that neither fixes a bug nor adds a feature',
    },
    {
      value: 'perf',
      name: 'perf:     A code change that improves performance',
    },
    { value: 'test', name: 'test:     Adds new or missing tests' },
    {
      value: 'chore',
      name:
        'chore:    Changes to the build process or auxiliary tools\n            and libraries such as documentation generation',
    },
    { value: 'revert', name: 'revert:   Revert to a commit' },
    { value: 'WIP', name: 'WIP:      Work in progress' },
  ],

  scopes: [],

  allowTicketNumber: true,
  isTicketNumberRequired: true,
  ticketNumberPrefix: 'EXP-',
  ticketNumberRegExp: '\\d{1,5}',

  messages: {
    type: "Select the type of change that you're committing:",
    scope: '\nDenote the SCOPE of this change (optional):',
    // used if allowCustomScopes is true
    customScope: 'Denote the SCOPE of this change:',
    subject: 'Write a SHORT, IMPERATIVE tense description of the change:\n',
    body: 'Provide a LONGER description of the change (optional). Use "|" to break new line:\n',
    breaking: 'List any BREAKING CHANGES (optional):\n',
    footer: 'List any ISSUES CLOSED by this change (optional). E.g.: #31, #34:\n',
    confirmCommit: 'Are you sure you want to proceed with the commit above?',
  },

  allowCustomScopes: true,
  allowBreakingChanges: ['feat', 'fix'],
  skipQuestions: ['footer', 'confirmCommit', 'scope'],

  subjectLimit: 100,
  askForBreakingChangeFirst: true, // default is false
}
```

**Comment by uglow** [comment]
Hi folks, I’m not sure why “hello: message” is not throwing an error. If ghooks / husky is installed properly, it should. I looked at the test cases and there isn’t specifically a test case for an invalid type without a scope. 

I also notice that `cz-customizable` Has changed quite a bit. For example, it allows you to add a type prefix and suffix, which this code does not expect. 

I’m pretty busy at the moment, so I don’t have the time to investigate further. The codebase is small - you may wish to contribute a PR to fix the problem yourself.

**Comment by uglow** [comment]
Amazingly, I've had some time to address this. I've updated the readme and noticed that the latest `husky` package.json config had changed, so that's fixed. I've also added an `examples` folder for both `husky` and `ghooks` to show how this package works with those packages. Please have a look at this and compare it to your setup. Please use v2.0.0 (I had the usual sem-ver naming issues - v1.6.0 is identical). 

In terms of contributing, the code has been re-written and avoids a lot of the tricky mocks that were necessary to test it. We use a function pipeline with a parameter object passed down through the pipelines. Makes testing & maintaining much easier.

**Comment by C0ZEN** [comment]
@uglow @dmwelch I had to add this line `"commit-msg": "cz-customizable-ghooks",` inside husky to make it works.
By the way your example is using husky inside the `package.json` but I can confirm that this is also working for `.huskyrc` config file.
Thank you for the time given on that!
