### ISSUE TITLE
Could we make it `getIssueFromBranch` optional or configurable?

### ISSUE THREAD

**Issue by leonardoanalista** [uglow/cz-customizable-ghooks#2]
I noticed after multiple commit amends you end up with many repeated lines with the branch name.
Also the team is getting in the habit of using the `ISSUES CLOSED` question for this.

**Comment by uglow** [comment]
Yes, good idea.

**Comment by uglow** [comment]
I can add support for a flag in this repo called `appendBranchNameToCommitMessage` which currently defaults to true. But it should be documented in the `cz-customizable` repo?

**Comment by leonardoanalista** [comment]
Thank you Brett, I am going to add to the cz-customizable README file. 
cheers
Leonardo

**Comment by Guria** [comment]
I think it must be documented in this repo README, because this setting for feature provided by this package.

**Comment by leonardoanalista** [comment]
Yes, it makes sense. What if we document it here and also mention on `cz-customizable`?
