### ISSUE TITLE
Doesn't look for ".cz-config.js" file

### ISSUE THREAD

**Issue by RebeccaStevens** [uglow/cz-customizable-ghooks#20]
Hey, I'm completely new to cz-customizable (so I could be doing something wrong) and I'm trying to set it up in my project but I'm getting the following error:

> cz-customisable config not specified in package.json!

I assume this package is only looking in package.json and not looking for the cz-config files. Could this feature be added? I prefer not to full my package.json file with config settings where possible.

**Comment by uglow** [comment]
Hi @RebeccaStevens , the message might mean you need to *reference* the cz-customizable config in your package.json, rather than inline your entire config into your package.json. For example:

`package.json:`
```
...
"config": {
    "cz-customizable": {
      "config": "commitMessageConfig.js"
    }
  }
  ...
  ```

**Comment by uglow** [comment]
I will close for now unless the above approach does not resolve your issue.

**Comment by RebeccaStevens** [comment]
Your solution probably will work but I would prefer not to put anything in the `package.json` file at all - like what I can do with the non-customizable version.

**Comment by uglow** [comment]
I’ll gladly accept a PR to provide this capability 👍🏻
